services:
  - type: web
    name: ethereum-withdrawal-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: API_VERSION
        value: 2.0.0
      - key: ETHEREUM_API_KEY
        value: 13fa508ea913c8c045a462ac
      - key: WALLET_ADDRESS
        value: 0xB5c1baF2E532Bb749a6b2034860178A3558b6e58
      - key: ENS_NAME
        value: Obasimartins65.eth
      - key: CHAIN_ID
        value: 1
      - key: RPC_ENDPOINT
        value: https://ethereum-rpc.publicnode.com
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: SECRET_KEY
        value: your-secret-key-change-in-production
    domains:
      - ethereum-withdrawal-api.onrender.com
